# Generated by Django 4.2.7 on 2023-11-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.URLField(default='https://forms.gle/BXKTFjTNGekH4S7q9'),
        ),
    ]
